services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5439:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_PASSWORD: test123